name: Packaging

on:
  release:
    types: [released]


jobs:
  winget:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup winget-create
        shell: powershell
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
      - name: Parse release version from github reference
        run: Set-Item -PATH Env:\GITHUB_CLI_VERSION -Value ${{ github.ref }}.substring(1) 
      - name: Update manifest
        shell: powershell
        run: |
            wingetcreate.exe update --id GitHub,Inc.GitHubCLI --url https://github.com/cli/cli/releases/download/v$env:GITHUB_CLI_VERSION/gh_${env:GITHUB_CLI_VERSION}_windows_amd64.msi --version ${env:GITHUB_CLI_VERSION} --out .\manifest\
      - name: Submit Pull Request to Winget Pkg
        shell: powershell
        run: wingetcreate.exe submit .\manifest\